config/routes.rb
Rails.application.routes.draw do
  get 'dashboard', to: 'dashboard#index'
  devise_for :users
  resources :users
  resources :billings
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/billing.rb
class Billing < ApplicationRecord
end

app/models/role.rb
class Role < ApplicationRecord
has_and_belongs_to_many :users, :join_table => :users_roles


belongs_to :resource,
           :polymorphic => true,
           :optional => true


validates :resource_type,
          :inclusion => { :in => Rolify.resource_types },
          :allow_nil => true

scopify
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/billings_controller.rb
class BillingsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_billing, only: [:show, :edit, :update, :destroy]

  # GET /billings
  # GET /billings.json
  def index
    @billings = Billing.all
  end

  # GET /billings/1
  # GET /billings/1.json
  def show
  end

  # GET /billings/new
  def new
    @billing = Billing.new
  end

  # GET /billings/1/edit
  def edit
  end

  # POST /billings
  # POST /billings.json
  def create
    @billing = Billing.new(billing_params)

    respond_to do |format|
      if @billing.save
        format.html { redirect_to @billing, notice: 'Billing was successfully created.' }
        format.json { render :show, status: :created, location: @billing }
      else
        format.html { render :new }
        format.json { render json: @billing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /billings/1
  # PATCH/PUT /billings/1.json
  def update
    respond_to do |format|
      if @billing.update(billing_params)
        format.html { redirect_to @billing, notice: 'Billing was successfully updated.' }
        format.json { render :show, status: :ok, location: @billing }
      else
        format.html { render :edit }
        format.json { render json: @billing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /billings/1
  # DELETE /billings/1.json
  def destroy
    @billing.destroy
    respond_to do |format|
      format.html { redirect_to billings_url, notice: 'Billing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_billing
      @billing = Billing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def billing_params
      params.require(:billing).permit(:name)
    end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def index
    @users =User.paginate(:page => page)
  end

  private

  def page
    params[:page].to_i || 1
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :to_dashboard
  layout :false

  def index
  end

  private

  def to_dashboard
    redirect_to(dashboard_path) unless !current_user.present?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/billings_helper.rb
module BillingsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/billings/_form.html.erb
<%= form_with(model: billing, local: true) do |form| %>
  <% if billing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(billing.errors.count, "error") %> prohibited this billing from being saved:</h2>

      <ul>
      <% billing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/billings/edit.html.erb
<h1>Editing Billing</h1>

<%= render 'form', billing: @billing %>

<%= link_to 'Show', @billing %> |
<%= link_to 'Back', billings_path %>

app/views/billings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Billings</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @billings.each do |billing| %>
      <tr>
        <td><%= billing.name %></td>
        <td><%= link_to 'Show', billing %></td>
        <td><%= link_to 'Edit', edit_billing_path(billing) %></td>
        <td><%= link_to 'Destroy', billing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Billing', new_billing_path %>

app/views/billings/new.html.erb
<h1>New Billing</h1>

<%= render 'form', billing: @billing %>

<%= link_to 'Back', billings_path %>

app/views/billings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @billing.name %>
</p>

<%= link_to 'Edit', edit_billing_path(@billing) %> |
<%= link_to 'Back', billings_path %>

app/views/dashboard/index.html.erb
<h1>Dashboard#index</h1>
<p>Find me in app/views/dashboard/index.html.erb</p>

app/views/layouts/_nav_bar.html.erb
<% if current_user.present? %>
  <% if current_user.roles.pluck(:name).include?('administrator') %>
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to('Dashboard', dashboard_path, class: 'nav-link') %>
      </li>
      <li class="nav-item">
        <%= link_to('Users', users_path, class: 'nav-link') %>

      </li>
      <li class="nav-item">
        <%= link_to('Billing', billings_path,class: 'nav-link') %>
      </li>
    </ul>
  <% else %>
  <% end %>
<% else %>
  <ul class="navbar-nav mr-auto">
    <li class="nav-item active">
      <a class="nav-link" href="#">Home</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#">Features</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#">Pricing</a>
    </li>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Easy Rental</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track'=> 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track'=> 'reload' %>
  </head>

  <body>

    <nav class="navbar navbar-expand-md navbar-light bg-light mb-4">
    <div class='container'>
    <%= link_to('Easy Rental', root_path,:class=>'navbar-brand')%>
    
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
     
         <%= render :partial => "layouts/nav_bar" %>
        <ul class="nav navbar-nav navbar-right">
        <% if current_user.present?%>
         <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="https://example.com"
             id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Account (<%= current_user.roles.pluck(:name).join(",") %>)</a>
            <div class="dropdown-menu" aria-labelledby="dropdown01">
              <a class="dropdown-item" href="/dashboard">Dashboard</a>
               <%= link_to('Sign out', destroy_user_session_path, method: :delete,class: 'dropdown-item') %>    
            </div>
          </li>
        <% else %>
      <li class="nav-item"><a  class="nav-link" href="/users/sign_up">Sign Up</a></li>
      <li class="nav-item"><a class="nav-link" href="/users/sign_in">Sign In</a></li>
      <% end%>
    </ul>
      </div>
      
      </div>
    </nav>
    <div class='container'>
    <%= yield %>
    </div>
  </body>
</html>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table class="table">
  <thead>
  <tr>
    <th>Name</th>
    <th>Mobile</th>
    <th>Country</th>
    <th>Email</th>
    <th>Role</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @users.each do |user| %>
    <tr>
      <td><%= user.last_sign_in_ip %></td>
      <td><%= user.last_sign_in_at %></td>
      <td><%= user.last_sign_in_at %></td>
      <td><%= user.email %></td>
      <td><%= user.roles.pluck(:name).join(",") %></td>

      <td><%= link_to 'Show', user %></td>
      <td><%#= link_to 'Edit', edit_billing_path(billing) %></td>
      <td><%#= link_to 'Destroy', billing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  </tbody>
</table>
<%= paginate @users %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>